<?php # main.php
#require_once ('./config.php');
include_once ('./header.php');
?>
<a name="EQUI"></a> <h2> Numerical Simulation of Equipotentials in an Electrolytic tank using the Relaxation Algorithm - Finite Difference Method</h2>
<p>
My College physic project which I wrote a program to simulate the experimental observations had the catchy name above. The experiment and the orignal simulation program(BASIC and Pascal) was devised and written by Dr. Mulligan. <br/>
I wrote my program initally in Modula-2 then converted it into Pascal which was the language of choice in the Physic Department and produced a number of iterations of this program to simulate points of equipotential in an electrolytic substance. The crude output which was stored in a txt file I read in to a program called "mongo" using Fortran and produced a snazzy graph. <br/>
Coming soon - results and TEX file of my formal report including code, which is on some 3.5inch floppy disk!!.<br/>
(I have tended to re-write this project, to learn a new language, e.g. C, Perl, or Java or Java with Swing.)</p>
<ul>
<li><a target="_blank" href="mongo1.jpg">Output Graph generated from table by mongo (1993)</a></li>
<li><a href="RelaxSim100.jar">Java Swing 100*100 Jar File with PlotGraph </a>(circa 2003 Java/Swing incarnation)</li>
<li><a target="_blank" href="Screenshot2all.png">Screenshot Output Generated by Swing App 100*100 array</a></li>
<li><a target="_blank" href="output100x100.csv">Output100x100.csv </a> Output from a Run of the Program in csv format</li>
<li><a target="_blank" href="Screenshot2middle.png">Output Generated by Swing App Middle array</a></li>
<li><a target="_blank" href="outputmiddle.csv">OutputMiddle.csv </a> Output of Middle from a Run of the Program in csv format</li>
<li><a href="RelaxSimOne.jar">Java Swing Jar File with PlotGraph </a>(circa 2003 Java/Swing incarnation)</li>
<li><a target="_blank" href="output.csv">Output.csv </a> Output from a Run of the Program in csv format</li>
<li><a target="_blank" href="Screenshot1.png">Screenshot Output Generated by Swing App array</a></li>
<li><a target="_blank" href="applets/RelaxSim100.html">Java Applet 100*100 File with PlotGraph </a>(circa 2000/2003)</li>
<li><a target="_blank" href="applets/RelaxSimOne.html">Java Applet with PlotGraph </a>(circa 2000/2003)</li>
<li><a target="_blank" href="equiperl.txt">Equipotentials Simulation in Perl</a> Perl Code with file write. (circa 1999)</li>
<li><a target="_blank" href="equi.cgi">Equipotentials Simulation in Perl run online</a> (takes some time to run)</li>
<li>equipotentials.mod</li>
<li>equipotentials.tex</li>
<li>equi.c (circa 1995 incarnation)</li>
<li>equi.java (circa 2000 incarnation)</li>
</ul>
<p>

<b>Recent Updates:</b></br>
<ul>
<li>Added Jar files.</li>
<li>Added Screenshots.</li>
<li>Java Swing Jar with Plotgraph can export a csv files.</li>
<li>Added Perl version from old windows machine.</li>
</ul>
</p>
<p>
<b>To Do:</b></br>
So much of this I must give it its own page, the iterations should flip between (1,1) to (100,100) and (100,100) to (1,1) to give it more balance? Add the re-run item to the 100*100, and radio buttons to the applet, and graph to WEST in Grid Layout.

</p>
<?php

include_once ('./footer.php');

?>
